# PulseAudio mínimo para el espejo de Huddle
load-module module-null-sink sink_name=raveroom sink_properties=device.description=Huddle
load-module module-native-protocol-unix socket=/tmp/pulse-native
